### ISSUE TITLE
Не работает синхронизация данных при установленном django-filters

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#291]
## Ожидаемое поведение
Ожидание, что синхрнизация данных успешно сработает.

## Текущее поведение
Выяснили, что при установленном django-filters не работает получение данных

```
my-new-feature ✗ $ make sync ARGS='hexlet-rus'
poetry run python manage.py fetchdata hexlet-rus
Data collection started
hexlet-rus
hexlet-rus/.github (1/2)
Empty repository
hexlet-rus/runit (2/2)
Processing issues and pull requests
Traceback (most recent call last):
  File "/tmp/hexlet-friends/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/tmp/hexlet-friends/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/tmp/hexlet-friends/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/tmp/hexlet-friends/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/tmp/hexlet-friends/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/hexlet-friends/contributors/management/commands/fetchdata.py", line 172, in handle
    create_contributions(
  File "/tmp/hexlet-friends/contributors/management/commands/fetchdata.py", line 41, in create_contributions
    for contrib in contrib_data:
  File "/tmp/hexlet-friends/contributors/utils/github_lib.py", line 104, in get_one_item_at_a_time
    response.raise_for_status()
  File "/tmp/hexlet-friends/.venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/hexlet-rus/hexlet-rus/runit/issues?page=1&per_page=100&state=all
make: *** [Makefile:60: sync] Ошибка 1
```

## Возможные решения
Нет представления

## Дейсвия по воспроизведению

Воспроизведено в ПРе https://github.com/Hexlet/hexlet-friends/pull/284
При этом другие зависимости не обновлялись
<details><summary>Details</summary>

```toml

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.1.9"
python-dotenv = "^0.20.0"
requests = "^2.31.0"
gunicorn = "^20.1.0"
dj-database-url = "^0.5"
whitenoise = "^6.2.0"
python-dateutil = "^2.8.2"
APScheduler = "^3.9.1"
django-crispy-forms = "^1.14.0"
django-cte = "^1.2.1"
psycopg2 = { version = "^2.8", optional = true }
psycopg2-binary = { version = "^2.9.3", optional = true }
PyJWT = "^2.4.0"
cryptography = "^41.0.0"
crispy-bootstrap5 = "^0.6"
django-extensions = "^3.2.1"
black = "^23.3.0"
django-debug-toolbar = "^3.8.1"
django-filter = "^23.2"
```
</details>

**Comment by fey** [comment]
нашли в чем дело)
