### ISSUE TITLE
Некорректное поведение фильтра "for the pas week" - "for the past month" в Top 10

### ISSUE THREAD

**Issue by Shvidunov** [Hexlet/hexlet-friends#292]
## Ожидаемое поведение
При переключении между фильтрами "for the pas week" и "for the past month" сохраняется выбранная вкладка поиска by  issues

## Текущее поведение
При переключении между фильтрами "for the pas week" и "for the past month" происходит переход с вкладки поиска by  issues на вкладку by commits

## Действия по воспроизведению

1. На главной страницу (EN) в форме Топ 10 выбрать вкладку by issues
2. Изменить период просмотра с for the past week на for the past month
3. проверить на какой вкладке находится таблица

## Информация о вашей системе

Win10, Chrome

## Информация об установленных зависимостях

    pip freeze

**Comment by NikGor** [comment]
Привет! Воспроизвел ошибку, возьму в работу

**Comment by fey** [comment]
@Shvidunov проверьте, пожалуйста, исправлена ли ошибка

**Comment by thiSSSnake** [comment]
Привет ! Ошибку не получилось воспроизвести, for the past week/month вообще не изменяют ничего, так и должно быть ? Если да то попробую решить и возьму issue, если нет, то в чем тогда проблем, и все равно возьму issue

![image](https://github.com/Hexlet/hexlet-friends/assets/119122372/cbcebd6e-dfb5-492d-9112-622a247490e7)

**Comment by fey** [comment]
@thiSSSnake вкладочки должны отвечать за вывод ишшусов и пулл реквестов за последний период. Давайте сделаем проще, будем выводить справа только новые ишшусы и пуллреквесты, допустим последние 10 штук. Уберем выборку "по неделе" и "по месяцу", те.. будут выводиться просто последние созданные ишшусы и пулл реквесты

**Comment by thiSSSnake** [comment]
окей, возьму в работу

**Comment by thiSSSnake** [comment]
Добавил реализацию вкладки "recently", там выводятся последние пулл реквесты и ишшусы, если устраивает - буду работать дальше и уберу фильтрацию по месяцу/неделе и оставлю только последние изменения
![image](https://github.com/Hexlet/hexlet-friends/assets/119122372/98cbdf8f-95bd-4800-ad50-f54f48c3ef36)

**Comment by fey** [comment]
@thiSSSnake давайте упраздним вкладки справа. группировки по неделям/месяцу имеют смысл если мы что-то агрегируем (наример топ репозиториев по колву ПРов), но тут у нас только последнее. ПОэтому проще выводить просто последние 10 записей.

**Comment by thiSSSnake** [comment]
@fey столкнулся с проблемой, после того как убираю вкладки справа, вкладки by pull request/issues перестают работать и просто возвращают на главную

**Comment by fey** [comment]
@thiSSSnake нипонятно. делайте пулл реквест, деплойте демку =)

**Comment by thiSSSnake** [comment]
@fey upd: я пофиксил, теперь на главной выводится справа только последние 10 пр и iss, нужно ли добавить в верстку название списка ? Или что-то поменять
![image](https://github.com/Hexlet/hexlet-friends/assets/119122372/fab9de0c-b298-4f95-ac95-90d0c47ab552)
![image](https://github.com/Hexlet/hexlet-friends/assets/119122372/f5720136-5f77-4052-ae76-5837b4be26ae)

**Comment by thiSSSnake** [comment]
@fey, сделаю пулл реквест, посмотрите на изменения пожалуйста :)

**Comment by fey** [comment]
@thiSSSnake смержил, но упала сборка. У меня на Рендере например такое

```
  • Installing sentry-sdk (1.41.0)
  • Installing wemake-python-styleguide (0.16.1)
  • Installing whitenoise (6.6.0)
Installing the current project: hexlet-friends (0.1.0)
The current project could not be installed: No file/folder found for package hexlet-friends
If you do not want to install the current project use --no-root
make collectstatic
make[1]: Entering directory '/opt/render/project/src'
poetry run python manage.py collectstatic --no-input
173 static files copied to '/opt/render/project/src/staticfiles'.
make[1]: Leaving directory '/opt/render/project/src'
make migrate
make[1]: Entering directory '/opt/render/project/src'
poetry run python manage.py migrate
Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/sentry_sdk/integrations/django/__init__.py", line 677, in connect
    return real_connect(self)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "dpg-cml48lacn0vc739mrsd0-a" to address: Name or service not known
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/render/project/src/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 117, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
       ^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 330, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 306, in _cursor
    self.ensure_connection()
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 288, in ensure_connection
    with self.wrap_database_errors:
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/sentry_sdk/integrations/django/__init__.py", line 677, in connect
    return real_connect(self)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: could not translate host name "dpg-cml48lacn0vc739mrsd0-a" to address: Name or service not known
make[1]: Leaving directory '/opt/render/project/src'
make[1]: *** [Makefile:54: migrate] Error 1
make: *** [Makefile:7: build-production] Error 2
==> Build failed 😞
==> Common ways to troubleshoot your deploy: https://docs.render.com/troubleshooting-deploys
```

Посмотрите-проверьте, пожалуйста и засылайте свежий ПР

**Comment by thiSSSnake** [comment]
@fey сейчас свежую версию деплою, посмотрю на работу и отправлю свежий пр

**Comment by thiSSSnake** [comment]
@fey ссылка на демо https://hexlet-friends-w4ta.onrender.com, отправляю свежий пр, должно работать .--.
